
package com.example.webserversetalarmtodo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetTodoNumWebserviceImpService", targetNamespace = "http://spring.service.getinfows.todoo.kmss.landray.com/", wsdlLocation = "http://156.8.11.13:6888/sys/webservice/getTodoNumWebservice?wsdl")
public class GetTodoNumWebserviceImpService
    extends Service
{

    private final static URL GETTODONUMWEBSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETTODONUMWEBSERVICEIMPSERVICE_EXCEPTION;
    private final static QName GETTODONUMWEBSERVICEIMPSERVICE_QNAME = new QName("http://spring.service.getinfows.todoo.kmss.landray.com/", "GetTodoNumWebserviceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://156.8.11.13:6888/sys/webservice/getTodoNumWebservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETTODONUMWEBSERVICEIMPSERVICE_WSDL_LOCATION = url;
        GETTODONUMWEBSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public GetTodoNumWebserviceImpService() {
        super(__getWsdlLocation(), GETTODONUMWEBSERVICEIMPSERVICE_QNAME);
    }

    public GetTodoNumWebserviceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETTODONUMWEBSERVICEIMPSERVICE_QNAME, features);
    }

    public GetTodoNumWebserviceImpService(URL wsdlLocation) {
        super(wsdlLocation, GETTODONUMWEBSERVICEIMPSERVICE_QNAME);
    }

    public GetTodoNumWebserviceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETTODONUMWEBSERVICEIMPSERVICE_QNAME, features);
    }

    public GetTodoNumWebserviceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetTodoNumWebserviceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGetTodoNumWebservice
     */
    @WebEndpoint(name = "GetTodoNumWebserviceImpPort")
    public IGetTodoNumWebservice getGetTodoNumWebserviceImpPort() {
        return super.getPort(new QName("http://spring.service.getinfows.todoo.kmss.landray.com/", "GetTodoNumWebserviceImpPort"), IGetTodoNumWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGetTodoNumWebservice
     */
    @WebEndpoint(name = "GetTodoNumWebserviceImpPort")
    public IGetTodoNumWebservice getGetTodoNumWebserviceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://spring.service.getinfows.todoo.kmss.landray.com/", "GetTodoNumWebserviceImpPort"), IGetTodoNumWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETTODONUMWEBSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw GETTODONUMWEBSERVICEIMPSERVICE_EXCEPTION;
        }
        return GETTODONUMWEBSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
