
package com.example.webserversetalarmtodo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IGetTodoNumWebservice", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGetTodoNumWebservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTodoOthers", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetTodoOthers")
    @ResponseWrapper(localName = "getTodoOthersResponse", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetTodoOthersResponse")
    public int getTodoOthers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoneSupervise", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetDoneSupervise")
    @ResponseWrapper(localName = "getDoneSuperviseResponse", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetDoneSuperviseResponse")
    public int getDoneSupervise(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTodoImissive", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetTodoImissive")
    @ResponseWrapper(localName = "getTodoImissiveResponse", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetTodoImissiveResponse")
    public int getTodoImissive(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoneImissive", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetDoneImissive")
    @ResponseWrapper(localName = "getDoneImissiveResponse", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetDoneImissiveResponse")
    public int getDoneImissive(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTodoSupervise", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetTodoSupervise")
    @ResponseWrapper(localName = "getTodoSuperviseResponse", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetTodoSuperviseResponse")
    public int getTodoSupervise(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setAlarmTodo", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.SetAlarmTodo")
    @ResponseWrapper(localName = "setAlarmTodoResponse", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.SetAlarmTodoResponse")
    public String setAlarmTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoneOthers", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetDoneOthers")
    @ResponseWrapper(localName = "getDoneOthersResponse", targetNamespace = "http://service.getinfows.todoo.kmss.landray.com/", className = "com.example.webserversetalarmtodo.GetDoneOthersResponse")
    public int getDoneOthers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
