
package com.example.webserversendtodo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISysNotifyTodoWebService", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISysNotifyTodoWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.webserversendtodo.NotifyTodoAppResult
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTodo", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.DeleteTodo")
    @ResponseWrapper(localName = "deleteTodoResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.DeleteTodoResponse")
    public NotifyTodoAppResult deleteTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        NotifyTodoRemoveContext arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.webserversendtodo.NotifyTodoAppResult
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTodoCount", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.GetTodoCount")
    @ResponseWrapper(localName = "getTodoCountResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.GetTodoCountResponse")
    public NotifyTodoAppResult getTodoCount(
        @WebParam(name = "arg0", targetNamespace = "")
        NotifyTodoGetCountContext arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.webserversendtodo.NotifyTodoAppResult
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setTodoDone", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.SetTodoDone")
    @ResponseWrapper(localName = "setTodoDoneResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.SetTodoDoneResponse")
    public NotifyTodoAppResult setTodoDone(
        @WebParam(name = "arg0", targetNamespace = "")
        NotifyTodoRemoveContext arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.webserversendtodo.NotifyTodoAppResult
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTodo", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.GetTodo")
    @ResponseWrapper(localName = "getTodoResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.GetTodoResponse")
    public NotifyTodoAppResult getTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        NotifyTodoGetContext arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.webserversendtodo.NotifyTodoAppResult
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendTodo", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.SendTodo")
    @ResponseWrapper(localName = "sendTodoResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.SendTodoResponse")
    public NotifyTodoAppResult sendTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        NotifyTodoSendContext arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.webserversendtodo.NotifyTodoAppResult
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTodo", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.UpdateTodo")
    @ResponseWrapper(localName = "updateTodoResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "com.example.webserversendtodo.UpdateTodoResponse")
    public NotifyTodoAppResult updateTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        NotifyTodoUpdateContext arg0)
        throws Exception_Exception
    ;

}
