
package com.example.webserverinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IGetChartWebservice", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGetChartWebservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubInfo", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetSubInfo")
    @ResponseWrapper(localName = "getSubInfoResponse", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetSubInfoResponse")
    public String getSubInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDubanInfo", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetDubanInfo")
    @ResponseWrapper(localName = "getDubanInfoResponse", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetDubanInfoResponse")
    public String getDubanInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMeetingInfo", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetMeetingInfo")
    @ResponseWrapper(localName = "getMeetingInfoResponse", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetMeetingInfoResponse")
    public String getMeetingInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPartyInfo", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetPartyInfo")
    @ResponseWrapper(localName = "getPartyInfoResponse", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetPartyInfoResponse")
    public String getPartyInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOnlineNum", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetOnlineNum")
    @ResponseWrapper(localName = "getOnlineNumResponse", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetOnlineNumResponse")
    public String getOnlineNum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrSendFile", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetOrSendFile")
    @ResponseWrapper(localName = "getOrSendFileResponse", targetNamespace = "http://service.getChart.todoo.kmss.landray.com/", className = "com.example.webserverinterface.GetOrSendFileResponse")
    public String getOrSendFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
